builds:
- goos:
  - linux
  - darwin
  goarch:
  - amd64
  env:
  - CGO_ENABLED=0

release:
  name_template: "v{{.Version}}"

#archive:
#  name_template: "{{.ProjectName}}-{{.Version}}-{{.Os}}-{{.Arch}}"
#  format: tar.gz
#  format_overrides:
#  - goos: windows
#    format: zip

checksum:
  name_template: "{{ .ProjectName }}-checksums.txt"
